
services:
  ros:
    image: ros-${ROS_DOCKER_DISTRO}
    container_name: ros-${ROS_DOCKER_DISTRO}-container
    build:
      context: ./images/${ROS_DOCKER_DISTRO}
      dockerfile: Dockerfile

    environment:
      - DISPLAY=$DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      # - XDG_RUNTIME_DIR=/tmp
      - XAUTHORITY=${XAUTH}
      # - ROS_MASTER_URI=http://$MASTER_IP:11311
      # - ROS_IP=$LOCAL_IP
      - TERM=$TERM

    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro

      - ${XSOCK}:${XSOCK}:rw # Display x11 socket
      - ${XAUTH}:${XAUTH}:r # x-server access

      - /home/$USER:/home/$USER


    working_dir: /home/$USER

    stdin_open: true
    tty: true
    user: ${UID}:${GID}
    # network_mode: host
    # command: /usr/bin/bash -c "source /opt/ros/noetic/setup.bash && roscore"


