
FROM osrf/ros:{{ROS_VERSION}}-desktop-full

ARG DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y\
    git\
    python3-pip\
    cmake\
    clang\
    bear\
    zsh\
    fd-find
