#!/usr/bin/bash
#vim: filetype=bash

SCRIPT_PATH=$(realpath "$0")
PROJECT_ROOT=$(dirname "$(dirname "$SCRIPT_PATH")")
: "${ROS_DOCKER_USER:=$(id -u)}"

if [ -z $SHELL ]; then
    SHELL="bash"
fi

source $PROJECT_ROOT/rid/common.bash
set_container_name

DOCKER_COMMAND="exec -u $ROS_DOCKER_USER -it $DOCKER_CONTAINER_NAME $SHELL"
# echo "$DOCKER_COMMAND"
docker $DOCKER_COMMAND


