#!/usr/bin/bash
#vim: filetype=bash

SCRIPT_PATH=$(realpath "$0")
PROJECT_ROOT=$(dirname "$(dirname "$SCRIPT_PATH")")

source $PROJECT_ROOT/rid/common.bash
set_container_name

DOCKER_CONTAINER_RUNNING=$(docker ps | grep $DOCKER_CONTAINER_NAME)
if [ -n "$DOCKER_CONTAINER_RUNNING" ]; then
    echo -n "Killing container: "
    docker kill $DOCKER_CONTAINER_NAME
fi

DOCKER_CONTAINER_EXIST=$(docker ps -a | grep $DOCKER_CONTAINER_NAME)
if [ -n "$DOCKER_CONTAINER_EXIST" ]; then
    echo -n "Removing container: "
    docker rm $DOCKER_CONTAINER_NAME
fi


